"""ajout_champs_user

Revision ID: 8e0ba2acc4d8
Revises: d11c48564ebd
Create Date: 2025-06-09 19:33:32.085846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0ba2acc4d8'
down_revision = 'd11c48564ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
